# Generated by Django 2.2.4 on 2019-08-21 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('school', models.TextField()),
                ('presenter', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
