# Generated by Django 2.2.4 on 2019-08-21 04:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_week', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='presenter',
        ),
        migrations.AddField(
            model_name='workshop',
            name='campus',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='workshop',
            name='day',
            field=models.DateField(blank=True, null=True, verbose_name='Day'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='know_or_bring',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshop',
            name='room',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='workshop',
            name='workshop_is_for',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workshop',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshop_week.School'),
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop_week.User')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop_week.Workshop')),
            ],
        ),
        migrations.CreateModel(
            name='PresenterGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop_week.User')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop_week.Workshop')),
            ],
        ),
        migrations.AddField(
            model_name='workshop',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshop_week.Category'),
        ),
    ]
