# Generated by Django 2.2.4 on 2019-08-21 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_week', '0002_auto_20190821_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='presenter',
            field=models.ManyToManyField(related_name='Presenter', to='workshop_week.User'),
        ),
        migrations.DeleteModel(
            name='PresenterGroup',
        ),
    ]
