# Generated by Django 2.2.4 on 2019-08-21 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_week', '0003_auto_20190821_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='day',
        ),
    ]
