# Generated by Django 2.2.4 on 2019-08-21 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_week', '0004_remove_workshop_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField()),
                ('year', models.IntegerField(default=2020)),
                ('start_date', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='school',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adminsiters', to='workshop_week.User'),
        ),
        migrations.AddField(
            model_name='school',
            name='name',
            field=models.CharField(default=None, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='short_name',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshop_week.School'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshop_week.Week'),
        ),
    ]
