# Generated by Django 2.2.4 on 2019-08-21 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_week', '0005_auto_20190821_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='description',
        ),
        migrations.AlterField(
            model_name='school',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administers', to='workshop_week.User'),
        ),
    ]
