# Generated by Django 2.2.4 on 2019-08-21 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_week', '0006_auto_20190821_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='attendees',
            field=models.ManyToManyField(related_name='Attendee', to='workshop_week.User'),
        ),
    ]
